app_id: "5fd5a6d3-78b7-4acd-b5bb-e3f7391ae649"
app_secret: "6Tl8Q~BcHOy0jCQ_O68wgCfoZ_gpvadi53KUZaHw"
redirect: "http://localhost:8000/callback"
scopes:
  - Application.ReadWrite.All
  - Directory.ReadWrite.All 
  - Directory.AccessAsUser.All
  - user.read
  - user.readwrite.all
  - mail.readwrite
authority: "https://login.microsoftonline.com/common"
schema_id: "extm96n9zk0_mailfiler"