# Generated by Django 3.2.15 on 2022-09-10 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailfiler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immutableId', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('bodyPreview', models.CharField(max_length=266)),
                ('sender', models.CharField(max_length=100)),
                ('receivedDateTime', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
