# Generated by Django 3.2.15 on 2022-09-16 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailfiler', '0003_auto_20220912_0503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immutableId', models.CharField(max_length=266)),
                ('name', models.CharField(max_length=266)),
                ('contentType', models.CharField(max_length=266)),
                ('size', models.IntegerField()),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailfiler.mail')),
            ],
        ),
    ]
