# Generated by Django 3.2.15 on 2022-09-28 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailfiler', '0005_connect_graphuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailfiler.graphuser'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailfiler.graphuser'),
        ),
    ]
