# Generated by Django 3.2.15 on 2022-10-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailfiler', '0006_auto_20220928_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='mail_type',
            field=models.CharField(default='inbox', max_length=266),
        ),
    ]
