# Generated by Django 3.2.15 on 2022-10-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailfiler', '0007_mail_mail_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='to',
            field=models.CharField(default='', max_length=266),
        ),
    ]
