# Generated by Django 3.2.15 on 2022-10-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailfiler', '0008_mail_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='receivedDateTime',
            field=models.DateTimeField(),
        ),
    ]
